# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inventory_pb2 as inventory__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryServiceStub(object):
    """=============================
    SERVICE
    =============================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/inventory.InventoryService/Login',
                request_serializer=inventory__pb2.LoginRequest.SerializeToString,
                response_deserializer=inventory__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.GetAllItems = channel.unary_unary(
                '/inventory.InventoryService/GetAllItems',
                request_serializer=inventory__pb2.GetAllRequest.SerializeToString,
                response_deserializer=inventory__pb2.GetAllResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/inventory.InventoryService/GetItem',
                request_serializer=inventory__pb2.GetItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.OrderItem = channel.unary_unary(
                '/inventory.InventoryService/OrderItem',
                request_serializer=inventory__pb2.OrderItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.OrderItemResponse.FromString,
                _registered_method=True)
        self.LLMCustomerQuery = channel.unary_unary(
                '/inventory.InventoryService/LLMCustomerQuery',
                request_serializer=inventory__pb2.LLMCustomerQueryRequest.SerializeToString,
                response_deserializer=inventory__pb2.LLMCustomerQueryResponse.FromString,
                _registered_method=True)
        self.AddItem = channel.unary_unary(
                '/inventory.InventoryService/AddItem',
                request_serializer=inventory__pb2.AddItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.AddItemResponse.FromString,
                _registered_method=True)
        self.UpdateItem = channel.unary_unary(
                '/inventory.InventoryService/UpdateItem',
                request_serializer=inventory__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.UpdateItemResponse.FromString,
                _registered_method=True)
        self.DeleteItem = channel.unary_unary(
                '/inventory.InventoryService/DeleteItem',
                request_serializer=inventory__pb2.DeleteItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.DeleteItemResponse.FromString,
                _registered_method=True)
        self.LLMProducerQuery = channel.unary_unary(
                '/inventory.InventoryService/LLMProducerQuery',
                request_serializer=inventory__pb2.LLMProducerQueryRequest.SerializeToString,
                response_deserializer=inventory__pb2.LLMProducerQueryResponse.FromString,
                _registered_method=True)
        self.GetItemStats = channel.unary_unary(
                '/inventory.InventoryService/GetItemStats',
                request_serializer=inventory__pb2.GetItemStatsRequest.SerializeToString,
                response_deserializer=inventory__pb2.GetItemStatsResponse.FromString,
                _registered_method=True)


class InventoryServiceServicer(object):
    """=============================
    SERVICE
    =============================
    """

    def Login(self, request, context):
        """Auth
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllItems(self, request, context):
        """Customer RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrderItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LLMCustomerQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddItem(self, request, context):
        """Producer RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """✅ Added correctly
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LLMProducerQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemStats(self, request, context):
        """NEW: Stats for LLM
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=inventory__pb2.LoginRequest.FromString,
                    response_serializer=inventory__pb2.LoginResponse.SerializeToString,
            ),
            'GetAllItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllItems,
                    request_deserializer=inventory__pb2.GetAllRequest.FromString,
                    response_serializer=inventory__pb2.GetAllResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=inventory__pb2.GetItemRequest.FromString,
                    response_serializer=inventory__pb2.GetItemResponse.SerializeToString,
            ),
            'OrderItem': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderItem,
                    request_deserializer=inventory__pb2.OrderItemRequest.FromString,
                    response_serializer=inventory__pb2.OrderItemResponse.SerializeToString,
            ),
            'LLMCustomerQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.LLMCustomerQuery,
                    request_deserializer=inventory__pb2.LLMCustomerQueryRequest.FromString,
                    response_serializer=inventory__pb2.LLMCustomerQueryResponse.SerializeToString,
            ),
            'AddItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AddItem,
                    request_deserializer=inventory__pb2.AddItemRequest.FromString,
                    response_serializer=inventory__pb2.AddItemResponse.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=inventory__pb2.UpdateItemRequest.FromString,
                    response_serializer=inventory__pb2.UpdateItemResponse.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=inventory__pb2.DeleteItemRequest.FromString,
                    response_serializer=inventory__pb2.DeleteItemResponse.SerializeToString,
            ),
            'LLMProducerQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.LLMProducerQuery,
                    request_deserializer=inventory__pb2.LLMProducerQueryRequest.FromString,
                    response_serializer=inventory__pb2.LLMProducerQueryResponse.SerializeToString,
            ),
            'GetItemStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemStats,
                    request_deserializer=inventory__pb2.GetItemStatsRequest.FromString,
                    response_serializer=inventory__pb2.GetItemStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.InventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """=============================
    SERVICE
    =============================
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/Login',
            inventory__pb2.LoginRequest.SerializeToString,
            inventory__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/GetAllItems',
            inventory__pb2.GetAllRequest.SerializeToString,
            inventory__pb2.GetAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/GetItem',
            inventory__pb2.GetItemRequest.SerializeToString,
            inventory__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OrderItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/OrderItem',
            inventory__pb2.OrderItemRequest.SerializeToString,
            inventory__pb2.OrderItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LLMCustomerQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/LLMCustomerQuery',
            inventory__pb2.LLMCustomerQueryRequest.SerializeToString,
            inventory__pb2.LLMCustomerQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/AddItem',
            inventory__pb2.AddItemRequest.SerializeToString,
            inventory__pb2.AddItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/UpdateItem',
            inventory__pb2.UpdateItemRequest.SerializeToString,
            inventory__pb2.UpdateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/DeleteItem',
            inventory__pb2.DeleteItemRequest.SerializeToString,
            inventory__pb2.DeleteItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LLMProducerQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/LLMProducerQuery',
            inventory__pb2.LLMProducerQueryRequest.SerializeToString,
            inventory__pb2.LLMProducerQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItemStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/GetItemStats',
            inventory__pb2.GetItemStatsRequest.SerializeToString,
            inventory__pb2.GetItemStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
