# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/llm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/llm.proto\x12\x03llm\"7\n\nLLMRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"\x1c\n\x0bLLMResponse\x12\r\n\x05reply\x18\x01 \x01(\t2@\n\nLLMService\x12\x32\n\rGetPrediction\x12\x0f.llm.LLMRequest\x1a\x10.llm.LLMResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LLMREQUEST']._serialized_start=24
  _globals['_LLMREQUEST']._serialized_end=79
  _globals['_LLMRESPONSE']._serialized_start=81
  _globals['_LLMRESPONSE']._serialized_end=109
  _globals['_LLMSERVICE']._serialized_start=111
  _globals['_LLMSERVICE']._serialized_end=175
# @@protoc_insertion_point(module_scope)
